name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Trigger on pushes to the master branch
  pull_request:
    branches:
      - master  # Trigger on PRs targeting the master branch

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12.4"  # Specify your Python version
    # Step 3 : Set up virtual env
    - name: Set up virtual environment
      run: python -m venv venv
      
    - name: Activate virtual environment
      run: venv/Scripts/activate

    # Step 4: Install dependencies
    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Install from requirements file

     # Step 5: Create .env file
    - name: Create .env file
      run: |
        echo "EMAIL=${{ secrets.EMAIL }}" >> .env
        echo "PASSWORD=${{ secrets.SECRET_PASSWORD }}" >> .env


    # Run tests
    - name: Run tests
      run: behave

 
